### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by vvvt** [marvinmann/gangOfTwo#1]
- [x] make the X-icon faster

- [x] animated color change upon [hovering](https://github.com/marvinmann/gangOfTwo/blob/master/vorgabe/screenshots/hover-nav-item.jpg)
- [x] resposive design ([switch to vertical dropdown layout](https://github.com/marvinmann/gangOfTwo/blob/master/vorgabe/screenshots/responsive-menue.jpg))
- [x] [sticky header](https://github.com/marvinmann/gangOfTwo/blob/master/vorgabe/screenshots/sticky-header.jpg)

- [x] finaly get how to move that fuking elements, you foolish piece of shit!!!

**Comment by vvvt** [comment]
Swearing is strongly discouraged and doesn't reflect the virtues and values of our enterprise!

**Comment by marvinmann** [comment]
Im awesome <3
