### ISSUE TITLE
generate map with Leaflet

### ISSUE THREAD

**Issue by vvvt** [marvinmann/gangOfTwo#17]
- [x] show a map by _Openstreetmaps_ with Leaflet
- [x] display a marker on every country _within the dataset_
- [x] display Popup/Tooltip when **clicking** a marker
- [x] popup shows the most recently changed chart's attribute
- [x] **at least** attribute name, country name, attribute value

**Comment by marvinmann** [comment]
The time has come! One For All *ESCALATION*
